---
- name: Verify network device configurations
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Show running configuration
      dcnos_command:
        commands: show running-config
      register: running_config

    - name: Display relevant configuration sections
      debug:
        msg: "{{ running_config.stdout_lines }}"
